name: Daily Video
on:
  schedule:
    - cron: '30 0 * * *'  # Roz subah 6 baje IST
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make Video
        run: |
          ffmpeg -f lavfi -i color=c=green:s=1280x720:d=8 -vf format=yuv420p auto_video.mp4
      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: village-video
          path: auto_video.mp4
